In [1]:
1+2

3

In [2]:
(1+2 * 3 -4)/5

0.6

In [3]:
2**8

256

In [4]:
x = 1
y = 1 /3
x * y

0.3333333333333333

In [5]:
Data_1 = 1 / 5
Data_2 = 3 / 5
Data_1 + Data_2

0.8

In [6]:
x = 1 / 3
print(x)
y = 2 / 3
print(y)

0.3333333333333333
0.6666666666666666


In [7]:
print('x = ' + str(x))

x = 0.3333333333333333


In [8]:
print('weight = {0} kg'.format(x))

weight = 0.3333333333333333 kg


In [9]:
type(100)

int

In [10]:
s=['SUN',1,'MON',2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [11]:
a = [[1,2,3],[4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [12]:
a = [[1,2,3],[4,5,6]]
print(a[0][1])

2


In [13]:
x = [1,1,2,3,5]
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [14]:
x = [1,1,2,3,5]
len(x)

5

In [15]:
y = range(5,10)
print(y[0],y[1],y[2],y[3],y[4])

5 6 7 8 9


In [16]:
z = list(range(5,10))
print(z)

[5, 6, 7, 8, 9]


In [17]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
a=(1,2,3)
print(a)

(1, 2, 3)


In [19]:
type(a)

tuple

In [22]:
x = 11
if x > 10:
    print('x is ') # ... (A1)
    print('    larger than 10.') # ...(A2)
else:
    print('x is smaller than 11') # ...(B1)


x is 
    larger than 10.


In [23]:
x > 10

True

In [24]:
type(x > 10)

bool

In [25]:
for i in [1,2,3]:
    print(i)

1
2
3


In [26]:
num = [2,4,6,8,10]
for i in range(len(num)):
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


In [27]:
num = [2,4,6,8,10]
for i, n in enumerate(num):
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


In [28]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [29]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [30]:
print(x)

[1 2 3]


In [31]:
y = np.array([4,5,6])
print(x + y)

[5 7 9]


In [32]:
type(x)

numpy.ndarray

In [33]:
x[0]

1

In [34]:
x[0] = 100
print(x)

[100   2   3]


In [36]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [38]:
a = np.array([1,1])
b = a
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [100   1]
b = [100   1]


In [39]:
a = np.array([1,1])
b = a.copy()
print('a = ' + str(a))
print('b = ' + str(b))
b[0] = 100
print('a = ' + str(a))
print('b = ' + str(b))

a = [1 1]
b = [1 1]
a = [1 1]
b = [100   1]


In [40]:
x = np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [41]:
x = np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [42]:
w, h = x.shape
print(w)
print(h)

2
3


In [43]:
x = np.array([[1,2,3],[4,5,6]])
x[1,2]

6

In [44]:
x = np.array([[1,2,3],[4,5,6]])
x[1,2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


In [45]:
print(np.zeros(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [47]:
print(np.zeros((2,10)))

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [48]:
print(np.ones((2,10)))

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [49]:
np.random.rand(2,3)

array([[ 0.11562088,  0.81134145,  0.70087627],
       [ 0.54955787,  0.01433457,  0.8455198 ]])

In [51]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [52]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])
print(x+y)

[[ 5  5  5]
 [10 10 10]]


In [54]:
x = np.array([[4,4,4],[8,8,8]])
print(10*x)

[[40 40 40]
 [80 80 80]]


In [55]:
x = np.array([[4,4,4],[8,8,8]])
print(np.exp(x))

[[   54.59815003    54.59815003    54.59815003]
 [ 2980.95798704  2980.95798704  2980.95798704]]


In [56]:
v = np.array([[1,2,3],[4,5,6]])
w = np.array([[1,1],[2,2],[3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]


In [57]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [58]:
print(x[5:])

[5 6 7 8 9]


In [59]:
print(x[3:8])

[3 4 5 6 7]


In [60]:
print(x[3:8:2])

[3 5 7]


In [61]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [62]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)
print(y[:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2]
 [5]]


In [63]:
x = np.array([1,1,2,3,5,8,13])
x > 3

array([False, False, False, False,  True,  True,  True], dtype=bool)

In [64]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


In [72]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

data=np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:3.2f}, std:{1:3.2f}'.format(data_mean, data_std))

mean:0.13, std:0.98


In [73]:
output = my_func3(data)
print(output)
print(type(output))
print('mean:{0:3.2f}, std:{1:3.2f}'.format(output[0],output[1]))

(0.13453904054104909, 0.97559003933114907)
<class 'tuple'>
mean:0.13, std:0.98


In [74]:
data = np.random.randn(5)
print(data)
np.save('datafile.npy',data) #保存
data = []
print(data)
data = np.load('datafile.npy') #ロード
print(data)

[-0.74054157  0.11869626 -0.70858353  0.13976205 -0.59720974]
[]
[-0.74054157  0.11869626 -0.70858353  0.13976205 -0.59720974]


In [75]:
# 複数のndarray型の保存
data1 = np.array([1,2,3])
data2 = np.array([10,20,30])
np.savez('datafile2.npz',data1=data1,data2=data2) #保存
data1 = [] #　データの初期化
data2 = []
outfile = np.load('datafile2.npz') #ロード
print(outfile.files) # 格納しているデータの表示
data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)


['data1', 'data2']
[1 2 3]
[10 20 30]
