In [3]:
# ベクトルを定義する
import numpy as np
a=np.array([2,1])
print(a)

[2 1]


In [2]:
type(a)

numpy.ndarray

In [4]:
#縦ベクトルを表す
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [5]:
d=np.array([[1],[2]])
print(d)

[[1]
 [2]]


In [6]:
print(d.T)

[[1 2]]


In [7]:
# 足し算と引き算
a = np.array([2,1])
b = np.array([1,3])
print(a + b)

[3 4]


In [8]:
a = np.array([2,1])
b = np.array([1,3])
print(a - b)

[ 1 -2]


In [10]:
# スカラーとの掛け算
print(2 * a)

[4 2]


In [12]:
b = np.array([1,3])
c = np.array([4,2])
print(b.dot(c))

10


In [13]:
a = np.array([1,3])
print(np.linalg.norm(a))

3.16227766017


In [14]:
import numpy as np
a = np.ones(1000)
b = np.arange(1,1001)
print(a.dot(b))

500500.0


In [ ]:
# 勾配を表す
import numpy as np
import matplotlib.pyplot as plt

# fの定義
def f(w0, w1):
    return w0**2 + 2 * w0 * w1 + 3

# fのw0に関する偏微分
def df_dw0(w0, w1):
    return 2 * w0 + 2 * w1

# fのw1に関する偏微分
def df_dw1(w0, w1):
    return 2 * w0 + 0 * w1

w_range = 2
dw = 0.25
w0 = np.arange(-w_range, w_range + dw, dw)
w1 = np.arange(-w_range, w_range + dw, dw)
wn = w0.shape[0]

ww0,ww1 = np.meshgrid(w0,w1)

ff = np.zeros((len(w0), len(w1)))
dff_dw0 = np.zeros((len(w0), len(w1)))
dff_dw1 = np.zeros((len(w0), len(w1)))

for i0 in range(wn):
    for i1 in range(wn):
        ff[i1,i0] = f(w0[i0],w1[i1])
        dff_dw0[i1,i0] = df_dw0(w0[i0],w1[i1])
        dff_dw0[i1,i0] = df_dw1(w0[i0],w1[i1])
        
plt.figure(figsize=(9,4))
plt.subplots_adjust(wspace=0.)
plt.subplot(1,2,1)
cont = plt.contour(ww0, ww1, ff, 10, colors='k')
cont.clabel(fmt='%2.0f',fontsize=8)
plt.xticks(range(-w_range, w_range + 1, 1))
plt.yticks(range(-w_range, w_range + 1, 1))
plt.xlim(-w_range - 0.5 , w_range + .5)
plt.ylim(-w_range - .5 , w_range + .5)
plt.xlabel('$w_0$',fontsize=14)
plt.ylabel('$w_1$',fontsize=14)

plt.subplot(1,2,2)
plt.quiver(ww0, ww1,dff_dw0, dff_dw1)
plt.xlabel('$w_0$',fontsize=14)
plt.ylabel('$w_1$',fontsize=14)

plt.xticks(range(-w_range, w_range + 1, 1))
plt.yticks(range(-w_range, w_range + 1, 1))

plt.xticks(range(-w_range, w_range + 1, 1))
plt.yticks(range(-w_range, w_range + 1, 1))

plt.show()